/*
 * Automatically generated by ./tools/auto_config_h. Please don't edit.  */

#ifndef __AUTO_CONFIGURATION_H__
#define __AUTO_CONFIGURATION_H__


#define MODULES_COMP_LZMA 	 1
#define BOOT_METHOD_SPI 	 1
#define USE_ROMTER 	 1
#define DYNAMIC_DRAM_PARAM 	 1
#define SEC_DOWNLOAD 	 1
#define SEC_GAP_RAM 	 1
#define SEC_GAP 	  4096
#define IC_VER_QCE491 	 1
#define IC_SIMPLE_TEST_NONE 	 1
#define RISCNUM 	  0
#define FIRSTBOOT_SIZE 	  65536
#define FIRSTBOOT_VVT_OFFSET 	  0x00000084
#define SCS_AREA_SIZE 	  65536
#define SYSTEM_WATCHDOG_EN 	 1
#define DEBUG_RELEASE 	 1
#define KERNEL_PREFIX 	  "release"
#define WRAP_MALLOC 	 1
#define MEM_FENCE 	 1
#define AP_MON 	 1
#define GL_OBJECT_LIST 	 1
#define GL_OBJECT_LIST_MUTEX 	 1
#define GL_OBJECT_LIST_SEMA 	 1
#define GL_OBJECT_LIST_FLAG 	 1
#define GL_OBJECT_LIST_QUEUE 	 1
#define GL_OBJECT_LIST_TIMER 	 1
#define GL_OBJECT_LIST_TASK 	 1
#define GL_OBJECT_LIST_COND 	 1
#define GL_OBJECT_LIST_LIST 	 1
#define GL_OBJECT_LIST_MEMPOOL 	 1
#define WRITE_PROTECT_SECTIONS 	 1
#define CUSTOMER_sunplus 	 1
#define CUSTOMER_NAME 	  "sunplus"
#define MODEL_BOARD_dvbs_evb 	 1
#define MODEL_BOARD_NAME 	  "dvbs_evb"
#define IC_SUPPORT_DRAM_A_16_H 	 1
#define IC_USE_DRAM_SIZE_256MB 	 1
#define DRAM_BUS_SINGLE 	 1
#define RAM_A_START 	  0x80000000
#define DRAM_A_SIZE_256 	 1
#define RAM_A_SIZE_MB 	  256
#define ROM_START 	  0x98000000

#endif

